package com.todo.dto;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
//Used for receiving employee data when adding a new employee.
public class EmployeeSaveDTO {
    private String employeeName;
    private String address;
    private String mobile;
    private boolean activeState;
}
/*Why No employeeId?

The employeeId is auto-generated by the database, so we don’t need it when creating a new employee.*/