package com.todo.dto;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
//Used for receiving employee data when adding a new employee.
public class EmployeeSaveDTO {
    private String employeeName;
    private String address;
    private String mobile;
    private boolean activeState;
    
    
	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public boolean isActiveState() {
		return activeState;
	}
	public void setActiveState(boolean activeState) {
		this.activeState = activeState;
	}
    
}
/*Why No employeeId?

The employeeId is auto-generated by the database, so we don’t need it when creating a new employee.*/
